### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by revolter** [nodes-vapor/aws#16]
Trying to build a project that includes this package throws this error:

    Cloning https://github.com/nodes-vapor/aws.git
    error: The dependency graph could not be satisfied. The package (https://github.com/nodes-vapor/aws.git) with version tag in range (1.0.0..<1.9223372036854775807.9223372036854775807) is not found. Found tags ([0.0.0, 0.1.0])

**Comment by johnrickman** [comment]
Make sure your the line is as such, .Package(url: "https://github.com/nodes-vapor/aws.git", majorVersion: 0, minor: 1)

**Comment by revolter** [comment]
Then the `README` should be changed appropriately.
