### ISSUE TITLE
Vapor 3 support

### ISSUE THREAD

**Issue by zdnk** [nodes-vapor/aws#35]
Is it coming?

**Comment by steffendsommer** [comment]
Hi @zdnk 

Thanks for reaching out. What parts of the functionality are you interested in? We're currently only planning on migrating the S3 part

**Comment by zdnk** [comment]
The S3 definitely. We will be starting new project soon and it will require AWS S3 to store the content.

**Comment by steffendsommer** [comment]
In that case, then yes. Have a look at https://github.com/nodes-vapor/readme/projects/2 for a better overview of what we're migrating and the current status.

**Comment by zdnk** [comment]
@steffendsommer I am also working on a more abstract version of your `Storage` https://github.com/zdnk/vapor-filesystem. Maybe we could join forces if you are interested. It is heavily inspired by https://github.com/thephpleague/flysystem, but I believe it brings more flexibility and wider usage than `Storage`.

**Comment by joscdk** [comment]
Maybe it would make sense to take a look at this, for the S3 connection stuff https://github.com/swift-aws/s3
